[package]
name = "msp-map-editor"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.17.3"
bevy-panic-handler = "6.0.0"
bevy_file_dialog = "0.9.0"
bevy_mod_imgui = { version = "0.8.0", features = ["docking"] }
grid = "1.0.0"
itertools = "0.14.0"
monostate = "1.0.2"
native-dialog = { version = "0.9.4", features = ["async"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.148"
serde_with = "3.16.1"

[profile.dev.package."*"]
opt-level = 3
